version: "3.9"

services:
  db:
    image: postgres
    container_name: db
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./data/db:/var/lib/postgresql/
  backend:
    container_name: backend
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    command:
      - /bin/sh
      - -c
      - |
        DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB} npm run migrate up
        npm run start
    volumes:
      - /home/node/app/node_modules
      - ./backend:/home/node/app
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - db
    tty: true

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command:
      - /bin/sh
      - -c
      - |
        npm run dev
    volumes:
      - /home/node/app/node_modules
      - ./frontend:/home/node/app
    ports:
      - "5173:5173"
    tty: true

networks:
  default:
